DECLARE_PCI_FIXUP_HEADER(PCI_VENDOR_ID_HUAWEI, 0x1105, quirk_disable_aspm_l0s_l1);

/*
 * Disable ASPM for Intel I225/I226 Ethernet controllers to prevent
 * intermittent PCIe link loss due to hardware errata.
 */
DECLARE_PCI_FIXUP_FINAL(PCI_VENDOR_ID_INTEL, 0x15F2, quirk_disable_aspm_l0s_l1); /* IGC_DEV_ID_I225_LM */
DECLARE_PCI_FIXUP_FINAL(PCI_VENDOR_ID_INTEL, 0x15F3, quirk_disable_aspm_l0s_l1); /* IGC_DEV_ID_I225_V */
DECLARE_PCI_FIXUP_FINAL(PCI_VENDOR_ID_INTEL, 0x15F8, quirk_disable_aspm_l0s_l1); /* IGC_DEV_ID_I225_I */
DECLARE_PCI_FIXUP_FINAL(PCI_VENDOR_ID_INTEL, 0x15F9, quirk_disable_aspm_l0s_l1); /* IGC_DEV_ID_I220_V */
DECLARE_PCI_FIXUP_FINAL(PCI_VENDOR_ID_INTEL, 0x3100, quirk_disable_aspm_l0s_l1); /* IGC_DEV_ID_I225_K */
DECLARE_PCI_FIXUP_FINAL(PCI_VENDOR_ID_INTEL, 0x3101, quirk_disable_aspm_l0s_l1); /* IGC_DEV_ID_I225_K2 */
DECLARE_PCI_FIXUP_FINAL(PCI_VENDOR_ID_INTEL, 0x3102, quirk_disable_aspm_l0s_l1); /* IGC_DEV_ID_I226_K */
DECLARE_PCI_FIXUP_FINAL(PCI_VENDOR_ID_INTEL, 0x3103, quirk_disable_aspm_l0s_l1); /* IGC_DEV_ID_I225_LMVP */
DECLARE_PCI_FIXUP_FINAL(PCI_VENDOR_ID_INTEL, 0x3104, quirk_disable_aspm_l0s_l1); /* IGC_DEV_ID_I226_LMVP */
DECLARE_PCI_FIXUP_FINAL(PCI_VENDOR_ID_INTEL, 0x3105, quirk_disable_aspm_l0s_l1); /* IGC_DEV_ID_I225_IT */
DECLARE_PCI_FIXUP_FINAL(PCI_VENDOR_ID_INTEL, 0x3106, quirk_disable_aspm_l0s_l1); /* IGC_DEV_ID_I226_LM */
DECLARE_PCI_FIXUP_FINAL(PCI_VENDOR_ID_INTEL, 0x3107, quirk_disable_aspm_l0s_l1); /* IGC_DEV_ID_I226_V */
DECLARE_PCI_FIXUP_FINAL(PCI_VENDOR_ID_INTEL, 0x3108, quirk_disable_aspm_l0s_l1); /* IGC_DEV_ID_I226_IT */
DECLARE_PCI_FIXUP_FINAL(PCI_VENDOR_ID_INTEL, 0x3109, quirk_disable_aspm_l0s_l1); /* IGC_DEV_ID_I221_V */
DECLARE_PCI_FIXUP_FINAL(PCI_VENDOR_ID_INTEL, 0x310A, quirk_disable_aspm_l0s_l1); /* IGC_DEV_ID_I226_BLANK_NVM */
DECLARE_PCI_FIXUP_FINAL(PCI_VENDOR_ID_INTEL, 0x310B, quirk_disable_aspm_l0s_l1); /* IGC_DEV_ID_I225_BLANK_NVM */
